# Generated by Django 4.1.6 on 2023-02-06 13:05

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chief_Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ф.И.О.')),
                ('pin_passport', models.CharField(max_length=14, verbose_name='ПИН-КОД паспорта')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('work_experience', models.IntegerField(verbose_name='Стаж работы')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Главный врач',
                'verbose_name_plural': 'Главные врачи',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(default=0, max_length=555)),
                ('employees', models.CharField(max_length=100, verbose_name='Сотрудники')),
                ('public_private', main.models.CustomBooleanField(default=True, verbose_name='Государственная')),
            ],
            options={
                'verbose_name': 'Больница',
                'verbose_name_plural': 'Больницы',
            },
        ),
        migrations.CreateModel(
            name='Okpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okpo', models.IntegerField(db_index=True, unique=True, verbose_name='ОКПО')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ф.И.О.')),
                ('pin_passport', models.CharField(max_length=14, verbose_name='ПИН-КОД паспорта')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Номер телефона')),
                ('diagnosis', models.TextField(verbose_name='Причина обращения в больницу')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chief_physician', verbose_name='Жалоба')),
                ('okpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hospital', verbose_name='ОКПО')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ф.И.О.')),
                ('pin_passport', models.CharField(max_length=14, verbose_name='ПИН-КОД паспорта')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Номер телефона')),
                ('okpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hospital', verbose_name='ОКПО')),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patients', verbose_name='Пациенты')),
            ],
            options={
                'verbose_name': 'Медсестра',
                'verbose_name_plural': 'Медсестры',
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='okpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.okpo', verbose_name='ОКПО'),
        ),
        migrations.AddField(
            model_name='chief_physician',
            name='okpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hospital', verbose_name='ОКПО'),
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('direction', models.DateTimeField(max_length=200, verbose_name='Направление')),
                ('therapist_surgeon', models.BooleanField(default=True, verbose_name='Терапевт')),
                ('name', models.CharField(max_length=200, verbose_name='Ф.И.О.')),
                ('pin_passport', models.CharField(max_length=14, verbose_name='ПИН-КОД паспорта')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('work_experience', models.IntegerField(verbose_name='Стаж работы')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Номер телефона')),
                ('nurse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.nurse', verbose_name='Медсестра')),
                ('okpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hospital', verbose_name='ОКПО')),
                ('patients', models.ManyToManyField(to='main.patients', verbose_name='Пациенты')),
            ],
            options={
                'verbose_name': 'Лечащий врач',
                'verbose_name_plural': 'Лечащие врачи',
            },
        ),
        migrations.AddField(
            model_name='chief_physician',
            name='therapist',
            field=models.ManyToManyField(to='main.therapist', verbose_name='Лечащий врач'),
        ),
    ]
