# Generated by Django 4.1.6 on 2023-02-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_patients_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='complaint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.chief_physician', verbose_name='Жалоба'),
            preserve_default=False,
        ),
    ]
