# Generated by Django 4.1.6 on 2023-02-06 13:38

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_patients_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='therapist_surgeon',
            field=main.models.CustomBooleanField(default=True, verbose_name='Терапевт'),
        ),
    ]
